import Link from "next/link";
import { Clipboard, Settings, Timer } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { RosterBoard } from "@/components/league/roster-board";
import { StandingsTable } from "@/components/league/standings-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getLeagueDashboard } from "@/lib/queries";

export default async function LeaguePage({ params }: { params: Promise<{ leagueId: string }> }) {
  const { leagueId } = await params;
  const { league, members, standings, picks, teams, players, scoreEvents, isDemo } = await getLeagueDashboard(leagueId);

  if (!league) {
    return <AppShell><div className="container py-10">League not found.</div></AppShell>;
  }

  return (
    <AppShell>
      <div className="container space-y-6 py-6">
        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Badge>{isDemo ? "Demo data" : "Supabase"}</Badge>
              <Badge className="bg-primary text-primary-foreground">Invite {league.invite_code}</Badge>
            </div>
            <h1 className="text-3xl font-semibold tracking-tight">{league.name}</h1>
            <p className="text-muted-foreground">{members.length} managers - {league.roster_team_slots} teams and {league.roster_player_slots} players per roster</p>
          </div>
          <div className="flex gap-2">
            <Button asChild variant="secondary">
              <Link href={`/leagues/${league.id}/settings`}>
                <Settings className="h-4 w-4" />
                Scoring
              </Link>
            </Button>
            <Button asChild>
              <Link href={`/leagues/${league.id}/draft`}>
                <Timer className="h-4 w-4" />
                Open Draft
              </Link>
            </Button>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader>
              <CardDescription>Members</CardDescription>
              <CardTitle>{members.length}/{league.max_members}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <CardDescription>Scoring</CardDescription>
              <CardTitle>{league.scoring_mode === "team_pickem" ? "Team Pick'em" : league.scoring_mode === "player_pickem" ? "Player Pick'em" : "Combo"}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader>
              <CardDescription>Invite Code</CardDescription>
              <CardTitle className="flex items-center gap-2">
                <Clipboard className="h-5 w-5" />
                {league.invite_code}
              </CardTitle>
            </CardHeader>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Standings</CardTitle>
            <CardDescription>Backed by recalculatable score events.</CardDescription>
          </CardHeader>
          <CardContent>
            <StandingsTable standings={standings} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Scoring Details</CardTitle>
            <CardDescription>Latest point events generated by the scoring engine.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {scoreEvents.length ? (
              scoreEvents.map((event) => {
                const member = members.find((item) => item.id === event.league_member_id);
                return (
                  <div key={event.id} className="flex items-center justify-between rounded-md border p-3 text-sm">
                    <div>
                      <div className="font-medium">{member?.display_name ?? "Manager"} - {event.description}</div>
                      <div className="text-xs text-muted-foreground">{event.category.replace(/_/g, " ")}</div>
                    </div>
                    <div className="font-semibold">{Number(event.points).toFixed(1)}</div>
                  </div>
                );
              })
            ) : (
              <p className="text-sm text-muted-foreground">No score events yet. Open scoring settings and recalculate after matches have final results.</p>
            )}
          </CardContent>
        </Card>

        <section>
          <h2 className="mb-3 text-xl font-semibold">Rosters</h2>
          <RosterBoard members={members} picks={picks} teams={teams} players={players} />
        </section>
      </div>
    </AppShell>
  );
}
